name: Continuous Integration for ci-c-util

on:
  push:
  pull_request:
  schedule:
  - cron:  '0 0 * * *'

jobs:
  ci-c-util-action-test:
    name: Test the C-Util CI action
    runs-on: ubuntu-latest

    steps:
    - name: Fetch Sources
      uses: actions/checkout@v2
    - name: Fetch a C-Util Project for Testing
      uses: actions/checkout@v2
      with:
        repository: c-util/c-rbtree
        ref: master
        path: c-rbtree

    - name: Run the C-Util CI (no m32, no valgrind)
      uses: ./src/ci-c-util
      with:
        source: c-rbtree
        m32: 0
        valgrind: 0

    - name: Run the C-Util CI (no m32, valgrind)
      uses: ./src/ci-c-util
      with:
        source: c-rbtree
        m32: 0
        valgrind: 1

    - name: Run the C-Util CI (m32, no valgrind)
      uses: ./src/ci-c-util
      with:
        source: c-rbtree
        m32: 1
        valgrind: 0

    - name: Run the C-Util CI (m32, valgrind)
      uses: ./src/ci-c-util
      with:
        source: c-rbtree
        m32: 1
        valgrind: 1
